#cloud-config
users:
  - name: user
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFbUbFFMOV4SKX3B5Jo/1tWXa6kNhRdLoGpQtTB7/uuG suijs@bu.edu

ssh_pwauth: false

package_update: true
package_upgrade: true

packages:
  - python3-pip
  - openssh-server
  - nmap
  - openssh-client
  - python3
  - python3-pip
  - ansible
  - git
  - curl
  - wget
  - vim


runcmd:
  - sudo pip3 install tensorflow==2.13.0 torch==2.0.1 torchvision==0.15.2 numpy==1.24.3 scipy==1.10.1 pandas==2.0.3 scikit-learn==1.3.0 matplotlib==3.7.2 seaborn==0.12.2 Pillow==10.0.0 opencv-python==4.8.0.74 nltk==3.8.1 transformers==4.30.2 jupyter==1.0.0 tqdm==4.65.0

