#cloud-config
users:
  - name: user # change this to the username you wish
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      # CHANGE THIS SSH KEY
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFbUbFFMOV4SKX3B5Jo/1tWXa6kNhRdLoGpQtTB7/uuG suijs@bu.edu

ssh_pwauth: false

package_update: true
package_upgrade: true


# Install basic packages
packages:
  - python3-pip
  - openssh-server
  - nmap
  - openssh-client
  - python3
  - python3-pip
  - ansible
  - git
  - curl
  - wget
  - vim

# Installing python packages
runcmd:
  - sudo pip3 install pandas numpy
