- name: update new data
  hosts: target_instance
  become: true
  vars_files:
    - /path/to/vars.yml
  tasks:
    - name: Remove /home/cynthus/workspace/data folder if it exists
      file:
        path: /home/cynthus/workspace/data
        state: absent
    - name: create and write service account file to path
      copy:
        src: "{{ storage_admin_src }}"
        dest: "{{ storage_admin_dest }}"
        mode: '0644'
        force: false
    - name: create and write service account file to path
      copy:
        src: "{{ artifact_src }}"
        dest: "{{ artifact_dest }}"
        mode: '0644'
        force: false
    - name: Ensure local data directory exists
      file:
        path: "{{ user_workspace_dir }}"
        state: directory
        mode: '0777'
    - name: Download dataset from GCS
      shell: |
          gsutil -m cp -r gs://{{ input_user_bucket }}/data {{ user_workspace_dir }}