---
- name: Install Docker on managed instances
  hosts: target_instance
  become: true  # Use sudo to install Docker
  vars_files:
    - /path/to/vars.yml
  roles:
    - docker-install
- name: run other dependencies 
  hosts: target_instance
  become: true
  vars_files:
    - /home/control/control-ansible/vars.yml
  tasks:
    - name: Install pip3 and required dependencies
      apt:
        name:
          - python3-pip
        state: present
    - name: Install docker-py and google-cloud-storage
      pip:
        name:
          - google-cloud-storage
          - docker
        state: present
    - name: create and write service account file to path
      copy:
        src: "{{ storage_admin_src }}"
        dest: "{{ storage_admin_dest }}"
        mode: '0644'
    - name: create and write service account file to path
      copy:
        src: "{{ artifact_src }}"
        dest: "{{ artifact_dest }}"
        mode: '0644'