---
- name: Install Docker on managed instances
  hosts: gcp_role_managed
  become: true  # Use sudo to install Docker
  roles:
    - docker-install
- name: run container from GCP Artifact Registry
  hosts: gcp_role_managed
  become: true
  vars_files:
    - ../vars.yml
  tasks:
    - name: create and write service account file to path
      copy:
        src: "{{ artifact_b64_src }}"
        dest: "{{ artifact_b64_dest }}"
        mode: '0644'
    - name: authenticate with google cloud
      shell: "cat {{ artifact_b64_dest }} | docker login -u _json_key --password-stdin https://{{ gcp_repo_location }}-docker.pkg.dev"
      args:
        executable: /bin/bash
    - name: Pull the Docker image
      docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"
        source: pull
        state: present
    - name: Run the Docker container
      docker_container:
          name: user_container
          image: "{{ docker_image_name }}:{{ docker_image_tag }}"
          state: started
          restart_policy: always

