---
- name: run container from GCP Artifact Registry
  hosts: target_instance
  become: true
  vars_files:
    - /path/to/vars.yml
  tasks:
    - name: Remove old logs.txt file if it exists
      ansible.builtin.file:
        path: /path/to/logs.txt
        state: absent
    - name: Run the Docker container
      docker_container:
          name: user_container
          image: "{{ docker_image_name_src }}:{{ docker_image_tag }}"
          state: started
          restart_policy: on-failure
          restart_retries: 3
          auto_remove: no
          volumes:
          - /path/to/data:/cynthus-src/data
    - name: Wait for the container to exit
      ansible.builtin.shell:
        cmd: "sudo docker wait user_container"
      register: container_exit_code

    - name: Write standard Docker logs to logs.txt
      ansible.builtin.shell:
         cmd: "sudo docker logs user_container > /path/to/logs.txt"
      when: container_exit_code.rc == 0

    - name: Write error Docker logs to logs.txt
      ansible.builtin.shell:
         cmd: "sudo docker logs user_container 2>> /path/to/logs.txt"
      when: container_exit_code.rc != 0

    - name: Copy all files from container's /cynthus-src/ to host
      ansible.builtin.shell:
        cmd: |
          sudo docker cp user_container:/cynthus-src /home/cynthus/workspace/outputs
    - name: Move logs.txt to outputs folder
      ansible.builtin.shell:
        cmd: "sudo mv /home/cynthus/workspace/logs.txt /home/cynthus/workspace/outputs/logs.txt"
    - name: Create a tar archive of the outputs folder
      community.general.archive:
        dest: /home/cynthus/workspace/outputs.tar.gz
        path: /home/cynthus/workspace/outputs
        format: gz
        remove: false
        force_archive: true
    - name: copy zip file to bucket
      shell: |
          sudo gsutil cp -r /home/cynthus/workspace/outputs.tar.gz gs://{{ output_user_bucket }}/workspace/

    - name: send email notifications using cloud function
      shell: |
           curl -X POST https://email-user-531274461726.us-central1.run.app  -H "Content-Type: application/json" -d '{"uid": "{{ user_id_upper }}" }'