steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/create-vm', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/create-vm']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'create-vm'
      - '--image'
      - 'gcr.io/$PROJECT_ID/create-vm'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '333m'
      - '--timeout'
      - '540'
      - '--concurrency'
      - '1'
      - '--service-account'
      - '531274461726-compute@developer.gserviceaccount.com'
      - '--ingress'
      - 'all'

images:
  - 'gcr.io/$PROJECT_ID/create-vm'