#cloud-config
users:
  - name: cynthus
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: [admin, users, wheel]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDr/2fh1JOdncSFZF5kxT+ONLoiPX+VUozPalI7Q1Gr5 control@control-ansible

ssh_pwauth: false

package_update: true
package_upgrade: true


# Install basic packages
packages:
  - python3-pip
  - python3-dev  # Required for some pip packages
  - python3-venv
  - openssh-server
  - nmap
  - openssh-client
  - python3
  - ansible
  - git
  - curl
  - wget
  - vim
  - build-essential  # Required for some pip packages
  - software-properties-common
  - ca-certificates
  - apt-transport-https

runcmd:
  - until dpkg -l | grep -q python3; do sleep 5; done
  - until command -v python3 >/dev/null 2>&1; do sleep 5; done
  - mkdir -p /home/cynthus/venv
  - python3 -m venv /home/cynthus/venv
  - chown -R cynthus:cynthus /home/cynthus/venv
  - /home/cynthus/venv/bin/pip install --upgrade pip
  - /home/cynthus/venv/bin/pip install numpy tensorflow
  - chown -R cynthus:cynthus /home/cynthus/venv 
  - echo "Python venv setup complete" > /home/cynthus/venv_setup_complete
  - chown cynthus:cynthus /home/cynthus/venv_setup_complete
