steps:
  # Building the docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/create-vm-test", "."]

  # Pushing the docker image to GCR
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/create-vm-test"]

  # Deploying to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'create-vm-test'
      - '--image'
      - 'gcr.io/$PROJECT_ID/create-vm-test'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '333m'
      - '--timeout'
      - '540'
      - '--concurrency'
      - '1'
      - '--service-account'
      - '531274461726-compute@developer.gserviceaccount.com'
      - '--ingress'
      - 'all'

images:
  - 'gcr.io/$PROJECT_ID/create-vm-test'