---
# Tasks file for install-dependencies

# Verify connectivity to hosts
- name: Ping my hosts
  ansible.builtin.ping:

# Update and install system packages
- name: Update package cache
  apt:
    update_cache: yes

- name: Install Python3 and pip
  ansible.builtin.apt:
    name: 
      - python3
      - python3-pip
    state: present

# Install pipreqs
- name: Install pipreqs
  ansible.builtin.pip:
    name: pipreqs
    state: latest

# Generate and use requirements.txt
- name: Scan user project and output requirements.txt file
  command: pipreqs {{ code_directory }} --force
  args:
    chdir: "{{ code_directory }}"
  register: pipreqs_output
  changed_when: "'Successfully saved requirements file' in pipreqs_output.stdout"

- name: Check if requirements.txt file exists 
  stat:
    path: "{{ code_directory }}/requirements.txt"
  register: requirements

- name: Install dependencies from requirements.txt
  pip:
    requirements: "{{ code_directory }}/requirements.txt"
  when: requirements.stat.exists